network/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<str:id>", views.profile, name="profile"),
    path("follow", views.follow, name="follow"),
    path("following/posts", views.following, name="following"),
    path("edit", views.edit, name="edit"),
    path("like", views.likesx, name="likes"),
    path("profile/<str:id>/followers", views.follower, name="followers"),
    path("profile/<str:id>/following", views.following2, name="following2")
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.core.files.storage import FileSystemStorage
from django.db import models


class User(AbstractUser):
    follower = models.IntegerField(default=0)
    user_image = models.ImageField(null=True,blank=True,upload_to="user_profile_images/")
    user_description = models.TextField(null=True)

class posts(models.Model):
    User = models.ForeignKey(User,on_delete=models.CASCADE,related_name="User")
    content = models.TextField()
    likes = models.IntegerField(default=0)
    post_image = models.ImageField(null=True,blank=True,upload_to="images/")
    timestamp = models.DateTimeField(auto_now_add=True)


class likes(models.Model):
    User = models.ForeignKey(User,on_delete=models.CASCADE,related_name="User1")
    post = models.ForeignKey(posts,on_delete=models.CASCADE,related_name="post1")

class followers(models.Model):
    User = models.ForeignKey(User,on_delete=models.CASCADE,related_name="User2")
    follower_id = models.IntegerField() 

network/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
import json
from django.core.paginator import Paginator

from .models import User, posts, likes, followers


def index(request):
    form = ""
    sk = posts.objects.all().order_by('-id')
    lk=set()
    for dk in sk:
        lk.add(User.objects.get(id=f"{dk.User_id}"))
    paginator = Paginator(sk, 10) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    lik=None
    if request.user.is_authenticated:
        lik = likes.objects.filter(User_id=request.user.id)
    if request.user.is_authenticated:
        #form = PostForm()
        if request.method == 'POST':
            if request.POST.get('content') == "":
                return render(request, "network/index.html",{
    "posts":page_obj,
    "names":lk,
    "likes":lik,
    "Error":"Please add something to post."
})
            else:
                #formx = PostForm(request.POST,request.FILES)
                posts(User_id=request.user.id,content=request.POST.get('content'),post_image=request.FILES.get('post_image'),likes=0).save()
                return HttpResponseRedirect('/')
    
    return render(request, "network/index.html",{
        "posts":page_obj,
        "names":lk,
        "likes":lik,
        "form":form
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            print(request.FILES.get('user_image'))
            user = User(username=username, email=email, password=password,user_image=request.FILES.get('user_image'))
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "network/register.html")


def profile(request,id):
    if request.method=="GET":
        data = User.objects.get(id=id)
        fkx = True
        if not followers.objects.filter(User_id=id,follower_id=request.user.id):
            fkx = False
        else:
            fkx = True

        post = posts.objects.filter(User_id=id).order_by('-id')
        paginator = Paginator(post, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number) 
        following = followers.objects.filter(follower_id=id)
        followingx = len(following)
        follow = followers.objects.filter(User_id=id)
        followx = len(follow)
        lik=None
        if request.user.is_authenticated:
            lik = likes.objects.filter(User_id=request.user.id)
        return render(request, "network/profile.html",{
            "posts":page_obj,
            "userx": data,
            "name": data.username,
            "following": followingx,
            "followers": followx,
            "image":data.user_image,
            "id": int(id),
            "fkx":fkx,
            "likes":lik,
        })
    elif request.method=='POST':
        data = User.objects.get(id=request.user.id)
        url = reverse('profile', kwargs={'id': request.user.id})
        if request.POST.get('content'):
            data.user_description = request.POST.get('content')
        else:
             data.user_image = request.FILES.get('user_image2')
            
        data.save()
        return HttpResponseRedirect(url)
        


@login_required
def follow(request):
    if request.method=='POST':
        data = json.loads(request.body)
        if data.get('content')=='Follow':
            if not followers.objects.filter(User_id=data.get('id'),follower_id=request.user.id):
                sk=followers(User_id=data.get('id'),follower_id=request.user.id)
                sk.save()
                return JsonResponse({
                    "message": "following this User."
                }, status=201)

            else:
                return JsonResponse({
                    "message": "Already following."
                }, status=201)

        elif data.get('content') == 'Unfollow':
            if not followers.objects.filter(User_id=data.get('id'),follower_id=request.user.id):
                return JsonResponse({
                    "message": "Already Unfollowed"
                }, status=201)

            else:
                sk = followers.objects.filter(User_id=data.get('id'),follower_id=request.user.id)
                sk.delete()
                return JsonResponse({
                    "message": "You have unfollowed this user"
                }, status=201)

        else:
            return JsonResponse({
                    "message": "Please dont change the button value."
                }, status=400)

    else:
        return JsonResponse({
                        "message": "wrong request method"
                    }, status=400)


@login_required
def following(request):
    folk = followers.objects.filter(follower_id=request.user.id).order_by('-id')
    jk=[]
    for nk in folk:
        jk.append(nk.User_id)

    sk = posts.objects.filter(User_id__in=jk).order_by('-id')
    paginator = Paginator(sk, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number) 
    
    lk=set()
    for dk in sk:
        lk.add(User.objects.get(id=f"{dk.User_id}"))

    lik=None
    if request.user.is_authenticated:
        lik = likes.objects.filter(User_id=request.user.id)
    
    return render(request, "network/following.html",{
        "posts":page_obj,
        "names":lk,
        "likes":lik
    })

@login_required
def edit(request):
    if request.method=='POST':
        #data = json.loads(request.body)
        try:
            print(request.POST.get("post_id"))
            nk = posts.objects.get(id=request.POST.get("post_id"))
            if request.user.id == nk.User_id:
                nk.content = request.POST.get("content")
                if(request.FILES.get('post_image2')):
                    nk.post_image = request.FILES.get('post_image2')
                nk.save()
                return JsonResponse({
                        "message": "Post edited"
                    }, status=201)
            else:
                return JsonResponse({
                        "message": "Can't edit the Post"
                    }, status=400)
        except ObjectDoesNotExist:
            return JsonResponse({
                        "message": "Can't edit the Post"
                    }, status=400)
    else:
        return JsonResponse({
                        "message": "wrong request method"
                    }, status=400)
    



@login_required
def likesx(request):
    if request.method=='POST':
        data = json.loads(request.body)
        if data.get('content') == "Like":
            nk = likes.objects.filter(post_id=data.get('id'),User_id=request.user.id)
            if not nk:
                likes(post_id=data.get('id'),User_id=request.user.id).save()
                vk = posts.objects.get(id=data.get('id'))
                vk.likes = vk.likes + 1
                vk.save()
                return JsonResponse({
                    "message": "Post Liked",
                    "likes": posts.objects.get(id=data.get('id')).likes
                }, status=201)
            else:
                return JsonResponse({
                    "message": "Post already Liked"
                }, status=400)

        elif data.get('content') == "Unlike":
            nk = likes.objects.filter(post_id=data.get('id'),User_id=request.user.id)
            if not nk:
                return JsonResponse({
                    "message": "Post already unliked."
                }, status=400)
            else:
                nk.delete()
                vk = posts.objects.get(id=data.get('id'))
                vk.likes = vk.likes - 1
                vk.save()
                return JsonResponse({
                    "message": "Post Unliked",
                    "likes": posts.objects.get(id=data.get('id')).likes
                }, status=201)

        else:
            return JsonResponse({
                    "message": "There is some error"
                }, status=400)

    else:
        return JsonResponse({
                        "message": "wrong request method"
                    }, status=400)


@login_required
def follower(request,id):
    if request.method=='POST':
        print(request.user.id+int(id))
        if request.user.id==int(id):
            sk = followers.objects.filter(follower_id=request.user.id).order_by('-id')
            lk=[]

network/templates/network/followers.html
{% extends "network/layout.html" %}

{% block body %}
    <h1>{{ title }}</h1>
    {% for post in posts %}
    <div class="post">
        <a href="{% url 'profile' id=post.id %}" class="username">{{ post.username }}</a>
    </div>
    {% empty %}
    No Followers at the moment
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </span>
    
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>




{% endblock %}

network/templates/network/following.html
{% extends "network/layout.html" %}

{% block body %}
    <h1>Posts of followers</h1>
    {% for post in posts %}
    <div class="post">
        {% for name in names %}
        {% ifequal post.User_id name.id  %}
        <a href="{% url 'profile' id=name.id %}" class="username">{{ name.username }}</a>
        {% endifequal %}
        {% endfor %}
        <label class="time">{{ post.timestamp }}</label>
        <label class="content">{{ post.content }}</label>
        {% if post.post_image %}
        <img id="image" src="{{ post.post_image.url }}"/>
        {% endif %}
        <hr>
        <div class="like2">
            <a id="like2">likes:</a>
            <label class="likes">{{ post.likes }}</label>
        </div>
        {% if user.is_authenticated %}
        <div class="buttonsx">
        {% for like in likes %}
        {% ifequal like.post_id post.id %}
        <button class="like btn btn-primary btn-sm">Unlike</button>
        {% endifequal %}
        {% endfor %}
        <button class="like btn btn-primary btn-sm">Like</button>
        {% endif %}
        <form id="idm">
        <input type="hidden"  class="submitmv" value="{{post.id}}">
        </form>
        </div>
    </div>
    {% empty %}
    No Followers at the moment
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page=1" class="btn-primary btn-sm">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}" class="btn-primary btn-sm">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </span>
    
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}" class="btn-primary btn-sm">next</a>
                <a href="?page={{ posts.paginator.num_pages }}" class="btn-primary btn-sm">last &raquo;</a>
            {% endif %}
        </span>
    </div>




{% endblock %}

network/templates/network/following2.html
{% extends "network/layout.html" %}

{% block body %}
    <h1>followers</h1>
    {% for post in posts %}
    <div class="post">
        <a href="{% url 'profile' id=post.id %}" class="username">{{ post.username }}</a>
        {% if post.user_image %}
        <img id="image" src="{{ post.user_image.url }}" style="width: 10%; display: block; margin-right: 10px;" />
        {% endif %}
    </div>
    {% empty %}
    No Followers at the moment
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </span>
    
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>




{% endblock %}

network/templates/network/index.html
{% extends "network/layout.html" %}

{% block body %}
    {% if user.is_authenticated %}
    <div id="New">
    <h3>New Post</h3>
    <form id="newpost" action="{% url 'index' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <textarea id="ta" cols="100" rows="5" placeholder="write new post" name="content"></textarea>
        <div class="imagey">
            <a id="upload_image">upload Image:</a>
            <input type="file" id="myFile" name="post_image" accept="image/*" id="id_post_image">
        </div>
        <div class="submit-c">
        <input type="submit" class="btn btn-primary" id="submitc" value="Post">
    </div>
   
    </form>
</div>
<h3>Posts</h3>
{% endif %}
    {% for post in posts %}
    <div class="post">
        <div class="nk">
        {% for name in names %}
        {% ifequal post.User_id name.id  %}
        <a href="{% url 'profile' id=name.id %}" class="username">{{ name.username }}</a>
        {% endifequal %}
        {% endfor %}
        <label class="time">{{ post.timestamp }}</label>
        <label class="content">{{ post.content }}</label>
        {% if post.post_image %}
        <img id="image" src="{{ post.post_image.url }}" />
        {% endif %}
        <hr>
        <div class="like2">
        <a id="like2">likes:</a>
        <label class="likes">{{ post.likes }}</label>
        </div>
        {% if user.is_authenticated %}
        <div class="buttonsx">
        {% for like in likes %}
        {% ifequal like.post_id post.id %}
        
        <button class="like btn btn-primary btn-sm">Unlike</button>
        {% endifequal %}
        {% endfor %}
        <button class="like btn btn-primary btn-sm">Like</button>
        {% endif %}
        <form id="idm">
        <input type="hidden"  class="submitmv" value="{{post.id}}">
        </form>
        
        {% if user.is_authenticated %}
        {% ifequal post.User_id user.id %}
        {% else %}
         </div>
        {% endifequal %}
        {% ifequal post.User_id user.id %}
        <button class="edit btn btn-primary btn-sm">Edit</button>
    </div>
</div>
        <div class="Newx">
            <form class="newpost" enctype="multipart/form-data">
                {% csrf_token %}
                <textarea class="tx" cols="100" rows="5" placeholder="Edit your Post" name="content">{{ post.content }}</textarea>
                <input type="file" id="myFile" name="post_image2" accept="image/*">
                <input type="submit"  class="submitxc btn btn-primary" value="Save">
                <input type="submit"  class="submitv btn btn-primary" value="Cancel">
                <input type="hidden"  class="submitxv btn btn-primary" value="{{post.id}}">
            </form>
        </div>
        {% else %}
    </div>
        </div>
        {% endifequal %}
        {% else %}
    </div>
    {% endif %}
    </div>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page=1" class="btn-primary btn-sm">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}" class="btn-primary btn-sm">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </span>
    
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}" class="btn-primary btn-sm">next</a>
                <a href="?page={{ posts.paginator.num_pages }}" class="btn-primary btn-sm">last &raquo;</a>
            {% endif %}
        </span>
    </div>




{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'network/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'network/styles.css' %}">
        <script src="{% static 'network/network.js' %}"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' id=user.id %}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'following' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}
<div class="post dy">
    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>
</div>
{% endblock %}

network/templates/network/profile.html
{% extends "network/layout.html" %}

{% block body %}
    <h1>{{ name }}</h1>
    {% if image %}
        <img id="user_image" src="{{ image.url }}" />
    {% endif %}
    {% if user.is_authenticated %}
    {% ifnotequal id user.id %}
    {% else %}
    <form class="change_profile_pic" action="{% url 'profile' id=userx.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" id="myFile2" name="user_image2" accept="image/*">
        <input type="submit"  class="btn btn-primary btn-lg" value="Change Profile Pic">
    </form>
    {% endifnotequal %}
    {% endif %}
    {% ifequal id user.id %}
    {% else %}
    <div id="description_div" style="margin-top:2%;">
        {% if user.is_authenticated %}
        {% if fkx %}
        <button id="fkx" class="btn btn-primary btn-lg">Unfollow</button>
        {% else %}
        <button id="fkx" class="btn btn-primary btn-lg">Follow</button>
        {% endif %}
        {% endif %}
        {% if userx.user_description %}
        <p id="description">{{userx.user_description}}</p>
        {% endif %}
    {% endifequal %}
    {% if user.is_authenticated %}
    {% ifnotequal id user.id %}
    {% else %}
    <div id="description_div">
    {% if userx.user_description %}
    <p id="description">{{userx.user_description}}</p>
    <button id="edit_description" class="btn btn-primary btn-lg">Edit description</button>
    {% else %}
    <p id="description"></p>
    <button id="edit_description" class="btn btn-primary btn-lg">Write_Description</button>
    {% endif %}
    
    <form id="change_description" action="{% url 'profile' id=userx.id %}" method="POST">
        {% csrf_token %}
        <textarea id="ta" cols="100" rows="5" placeholder="write new post" name="content">{{userx.user_description}}</textarea>
        <button class="cancel_description btn btn-primary">Cancel</button>
        <input type="submit" class="btn btn-primary" id="submitck" value="Save">
    </form>
    <form id="followers" action="{% url 'followers' id=userx.id %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" id="submitc" value="Following">
    </form>
    <form id="following" action="{% url 'following2' id=userx.id %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" id="submitc" value="Followers">
    </form>
    {% endifnotequal %}
    {% endif %}
    <div id="followersx">
        followers: 
        <div id="follo">{{ followers }}</div>
    </div>
    <div id="followingx">
        following: 
        <div id="follok">{{ following }}</div>
    </div>
    <form action="">
        <input type="hidden" id='ido' value={{id}}>
    </form>
    <label id="hkj">{{ name }} Posts:</label>
</div>
    {% for post in posts %}
    <div class="post">
        <div class="nk">
        {% for name in names %}
        {% ifequal post.User_id name.id  %}
        <a class="username">{{ name.username }}</a>
        {% endifequal %}
        {% endfor %}
        <label class="time">{{ post.timestamp }}</label>
        <label class="content">{{ post.content }}</label>
        {% if post.post_image %}
        <img id="image" src="{{ post.post_image.url }}"/>
        {% endif %}
        <hr>
        <div class="like2">
            <a id="like2">likes:</a>
            <label class="likes">{{ post.likes }}</label>
        </div>
        {% if user.is_authenticated %}
        <div class="buttonsx">
        {% for like in likes %}
        {% ifequal like.post_id post.id %}
        <button class="like btn btn-primary btn-sm">Unlike</button>
        {% endifequal %}
        {% endfor %}
            <button class="like btn btn-primary btn-sm">Like</button>
        {% endif %}
            <form id="idm">
                <input type="hidden"  class="submitmv" value="{{post.id}}">
            </form>
        {% if user.is_authenticated %}
        {% ifequal post.User_id user.id %}
            <button class="edit btn btn-primary btn-sm">Edit</button>
        </div>
    </div>
        <div class="Newx">
            <form class="newpost" enctype="multipart/form-data">
                {% csrf_token %}
                <textarea class="tx" cols="100" rows="5" placeholder="Edit your Post" name="content">{{ post.content }}</textarea>
                <input type="file" id="myFile" name="post_image2" accept="image/*" id="id_post_image2">
                <input type="submit"  class="submitxc btn btn-primary" value="Save">
                <input type="submit"  class="submitv btn btn-primary" value="Cancel">
                <input type="hidden"  class="submitxv" value="{{post.id}}">
            </form>
        </div>
        {% else %}
        </div>
    </div>
        {% endifequal %}
        {% else %}
    </div>
    {% endif %}
    </div>
    {% empty %}
    No Posts at the moment
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page=1" class="btn btn-primary btn-sm">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}" class="btn btn-primary btn-sm">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </span>
    
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}" class="btn btn-primary btn-sm">next</a>
                <a href="?page={{ posts.paginator.num_pages }}" class="btn btn-primary btn-sm">last &raquo;</a>
            {% endif %}
        </span>
    </div>



{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}
<div class="post dy">
    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
   
    <form action="{% url 'register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <div class="form-group">
            <a>Upload your profile Image. (optional)</a>
            <input type="file" id="myFile" name="user_image" accept="image/*">
        </div>          
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>
</div>

{% endblock %}